name: Create and publish a package
on:
  push:
    branches: ['master']
jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkkout Files
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'
      - name: Build
        run: dotnetBuild
