name: Create and publish a package
on:
  push:
    branches: ['master']
jobs:
  publish-package-on-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkkout Files
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'
      - name: Build
        run: dotnet build
      - name: Package
        run: dotnet pack --configuration Release
      - name: Publish
        run: dotnet nuget push "bin/Release/Carlton.Base.Client.State.Abstractions.1.0.0.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/nicholas.galazzo@gmail.com/index.json"
      
